DEV: Update docs config
py-pdf/pypdf pull request #1430
Opened 2022-11-12 12:47 UTC by adehad

# Summary of changes:
1. [Added] Creates a tox env for docs generating
2. [Subjective, can be removed] Change theme to `furo` due to modern look and better maintenance
3. [Changed] conf.py to prepare for https://github.com/py-pdf/PyPDF2/discussions/1227

# Points of Note
There are about 250 warnings in the autogenerated docs, mainly this is because there are modules prefixed with underscores that are not autogenerated by default. Happy to further add to this PR to address these changes with your guidance, otherwise happy to make a separate PR.

2022-11-12 12:49 UTC, MartinThoma commented on docs/conf.py
> +import PyPDF2 as py_pkg
```suggestion
import PyPDF2 as py_pkg  # noqa
```

2022-11-12 12:50 UTC, MartinThoma commented
Why did you remove the bat file?

2022-11-12 12:52 UTC, adehad commented
> Why did you remove the bat file?

@MartinThoma As the `tox -e docs` is platform agnostic it obsoletes both

2022-11-12 20:51 UTC, adehad commented
Managed to shave off around 80 warnings by ignoring the `io` module references. For some reason they are picked up as being under the `_io` module by sphinx and then complains that the module doesn't exist

2022-11-19 08:30 UTC, MartinThoma requested changes
When I run `tox -e docs` it doesn't seem to generate anything. Besides several warnings, it generates:

```
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 165 warnings.
ERROR: InvocationError for command /home/moose/Github/py-pdf/PyPDF2/.tox/docs/bin/sphinx-build -a -n -v -W --keep-going -b html --color -d .tox/docs_doctree docs/ .tox/docs_out (exited with code 1)
__________________________________________________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________________________________________________
ERROR:   docs: commands failed
```

At the moment, I think this PR would break the documentation generation.

Did I do something wrong?

2022-11-19 08:44 UTC, MartinThoma commented
Regarding the switch to `furo`, I need to compare examples. I make some screenshots on my laptop as well as with the S20 size:

## readthedocs

Start page:

![image](https://user-images.githubusercontent.com/1658117/202842544-a7a426cd-3dc9-4fbb-ad12-53a407eccf66.png)


Start page (S20):

![image](https://user-images.githubusercontent.com/1658117/202842494-68d4f161-2860-44f1-af5c-a84c063346ed.png)

Navbar (S20):

![image](https://user-images.githubusercontent.com/1658117/202842464-6535ec1b-05ee-49eb-8829-a595ca8f1192.png)


Extract Text:

![image](https://user-images.githubusercontent.com/1658117/202842574-dab5bfa3-9c9c-4548-aa89-a27637e749be.png)


Extract Text (S20):

![image](https://user-images.githubusercontent.com/1658117/202842524-c8b9e72a-bd9a-414e-962f-8d2665de31d4.png)

PdfFileReader:

![image](https://user-images.githubusercontent.com/1658117/202842616-d75c26bd-b17c-4c5e-ad5d-44bc3afdd525.png)


PdfFileReader (S20):

![image](https://user-images.githubusercontent.com/1658117/202842429-c835e563-3f49-4f1b-a7ad-ea7172867056.png)


## furo

Start page:

![image](https://user-images.githubusercontent.com/1658117/202842656-461a5aa1-2a45-436e-83a9-6b8786ba7295.png)

Extract Text:

![image](https://user-images.githubusercontent.com/1658117/202842671-700611f4-3546-4099-a718-d0dda3688c50.png)

PdfFileReader:

![image](https://user-images.githubusercontent.com/1658117/202842693-048cff69-4550-4849-9f5d-8db345266b90.png)

Start Page (S20):

![image](https://user-images.githubusercontent.com/1658117/202842748-7ae6ffe5-7686-47e4-9cb3-d63afce78c71.png)

Navbar (S20):

![image](https://user-images.githubusercontent.com/1658117/202842725-7187b857-3ef2-4d0d-a98a-dc1ac7b00d26.png)


PdfFileReader (S20):

![image](https://user-images.githubusercontent.com/1658117/202842712-be81332c-1a8c-4181-b4d4-a59d547b8fef.png)

2022-11-19 08:46 UTC, MartinThoma commented
I like `sphinx_rtd_theme` better than `furo`. I also don't see any objective reason to switch (e.g. both look fine on mobile)

2022-11-19 11:16 UTC, adehad commented
Thanks for the review @MartinThoma 

> When I run `tox -e docs` it doesn't seem to generate anything. Besides several warnings, it generates:


The output docs should be in the folder
`.tox/docs_out` but happy to change. 


> At the moment, I think this PR would break the documentation generation.
> 
> Did I do something wrong?

The command I used treats warnings as errors, (which is usually what you want when running in CI, so contributors don't introduce more issues). So possible for me to remove that flag due to the current docs state. 




Also happy to move back to the rtd theme, the issue I've had with it is that: it doesn't get updated as regularly. So we had some issues when updating sphinx for example. Looking at the project now perhaps they have gotten some maintenance back in.

2022-11-19 13:02 UTC, adehad commented
hmm, just changing to draft as the docs build is running into an error with docutils

2022-11-19 13:07 UTC, adehad commented
false alarm it seems! Builds fine for me now, might be because of the cache from the previous docs build

2023-03-18 14:01 UTC, MartinThoma commented
Sorry it took that long. I'm ok with the tox changes, but please keep the Makefile / the make.bat:

1. I don't know if readthedocs would work with the current PR. Probably there is a way to make it work, but I don't have the energy to figure that out
2. Developers might want to build the docs locally (hence keeping also the bat file). I would be fine with removing the bat file if you added instructions to `docs/dev/documentation.md` how to generate the documentation with tox.

2023-03-23 12:34 UTC, adehad commented
@MartinThoma sounds good. Regarding the readthedocs, I can include a config file that can work. I can base it off work on another project I maintain:
https://github.com/pycontribs/jira/blob/main/.readthedocs.yml

It may also be helpful to configure the readthedocs app, so that this PR will include a link to the docs (which will help confirm it is working)

2023-03-25 07:55 UTC, MartinThoma commented
> I can include a config file that can work.

Currently the docs build just fine. Why should we change it?

> It may also be helpful to configure the readthedocs github actions app, so that this PR will include a link to the docs based on these changes (which will help confirm it is working)

What does it do / why is that a good idea?

2023-03-25 10:51 UTC, adehad commented
> > I can include a config file that can work.
> 
> Currently the docs build just fine. Why should we change it?

My experience suggests using a "configuration as code" approach is more maintainable. 
One example might be: contributors being able to suggest a fix for broken docs builds without them needing admin rights in readthedocs.

> 
> > It may also be helpful to configure the readthedocs github actions app, so that this PR will include a link to the docs based on these changes (which will help confirm it is working)
> 
> What does it do / why is that a good idea?

**What does it do**: For every pull request it builds the docs, and provides a preview link.
**Why is that a good idea:** I found it a good way to check how a contribution will change the docs and also refer a contributor to how the docs look after their change.

2023-03-26 10:10 UTC, MartinThoma commented
> configuration as code

Sounds good :+1: Please go ahead with adding that :-) 

As this PR already takes a while,  I would suggest to make small/single changes. That makes it a lot easier for me to test + decide to merge something. Adding a config file for read-the-docs might be a single simple PR.

2023-03-26 10:10 UTC, MartinThoma commented
> For every pull request it builds the docs, and provides a preview link.

That sounds amazing :heart_eyes:

2023-03-26 15:03 UTC, adehad commented
Cool, I've tidied up this to just be for tox changes, will leave the config for another PR

2023-03-28 07:58 UTC, adehad commented
Doc build failed on the readthedocs, but not reported yet
I will need to drop changes to `requirements/docs.txt` for the build to pass most likely

2023-06-11 08:32 UTC, MartinThoma commented
This is open for a long time now and I feel like it will never finish.

The current way of building the docs works, the current PR does not. Hence I close it.

Some of the changes you proposed were added in between. Thank you for the time and effort you put into it :pray:

2023-06-11 08:32 UTC, closed without merging