MAINT: Relax typing_extensions version
py-pdf/pypdf pull request #2104
Opened 2023-08-21 10:54 UTC by stefan6419846

This relaxes the version of `typing_extensions` required by PyPDF as proposed in #1950.

Please note that this change is not reflected in CI due to the reasons outlined in https://github.com/py-pdf/pypdf/issues/1950#issuecomment-1627387294, but I have tested it locally and some time ago on my fork of the project.

Closes #1950.

2023-08-24 18:31 UTC, MartinThoma requested changes
I tried this:

```
pyenv local 3.6.15
pip install typing_extensions==3.7.4.2
pytest
```

and got:

```
ImportError while loading conftest '/home/moose/Github/py-pdf/pypdf/tests/conftest.py'.
tests/__init__.py:7: in <module>
    from pypdf.generic import DictionaryObject, IndirectObject
pypdf/__init__.py:10: in <module>
    from ._encryption import PasswordType
pypdf/_encryption.py:46: in <module>
    from ._utils import logger_warning
pypdf/_utils.py:56: in <module>
    from typing_extensions import TypeAlias
E   ImportError: cannot import name 'TypeAlias'
```

Relaxing the typing_extensions version seems not easily possible. I'm rather skeptical of this change.

As it is, I will not accept it.

2023-08-24 18:51 UTC, stefan6419846 commented
As already mentioned, I have been testing this with every release on a local Python 3.6 installation with a Git checkout and did not see these issues, although using version 3.7.4.3. Did you try with 3.7.4.3 instead as well?

Additionally, this is the old GitHub Actions run I did over a month ago which did not show any problems as well: https://github.com/stefan6419846/pypdf/actions/runs/5495158775/job/14880601145 (the requirements file is https://github.com/stefan6419846/pypdf/blob/test01/requirements/ci.txt)

At the moment, I am creating patched wheels for every release and did not see any issues as well. Nevertheless, Python 3.6 is slowly being phased out in my case, so I would be okay with this not being merged - although I always prefer to use sensible and reasonable limits for package versions backed by actual facts, and Python 3.6 currently keeps being supported by PyPDF. (By the way: One of the culprits for `typing_extensions==3.7.4.3` in my case has been the Tensorflow version for Python 3.6, which places rather strict limits on its dependencies.)

2023-08-26 11:16 UTC, MartinThoma commented
I'll give it another shot when I'm back home (this weekend) :-)

2023-08-27 05:31 UTC, MartinThoma commented
Next try:

requirements-2104.txt:

```
attrs==20.3.0
coverage==6.2
dataclasses==0.8
flake8==5.0.4
flake8-bugbear==22.9.23
flake8-implicit-str-concat==0.2.0
flake8-print==4.0.1
fpdf2==2.4.1
importlib-metadata==4.2.0
iniconfig==1.1.1
mccabe==0.7.0
more-itertools==8.14.0
mypy==0.971
mypy-extensions==1.0.0
packaging==21.3
Pillow==8.4.0
pluggy==1.0.0
py==1.11.0
py-cpuinfo==9.0.0
pycodestyle==2.9.1
pycryptodome==3.18.0
pyflakes==2.5.0
pyparsing==3.1.1
pytest==7.0.1
pytest-benchmark==3.4.1
pytest-socket==0.4.1
pytest-timeout==2.1.0
six==1.16.0
tomli==1.2.3
typed-ast==1.5.5
typeguard==2.13.3
types-dataclasses==0.6.6
types-Pillow==10.0.0.2
typing-extensions==3.7.4.3  # <---- that is the critical part we want to test
zipp==3.6.0
```

then:

```
pyenv local 3.6.15
pip install -r requirements-2104.txt
pytest
```

Interestingly, it didn't work with `typing-extensions==3.7.4.2`, but did work with `typing-extensions==3.7.4.3` :thinking:

2023-08-27 06:18 UTC, MartinThoma commented
Found it: https://github.com/python/typing_extensions/issues/276 :tada: This took me about an hour -.-

2023-08-27 06:19 UTC, MartinThoma commented on pyproject.toml
> +    "typing_extensions >= 3.7.4.2; python_version < '3.10'",
```suggestion
    "typing_extensions >= 3.7.4.3; python_version < '3.10'",
```

2023-08-27 06:21 UTC, merged

2023-08-27 06:22 UTC, MartinThoma commented
Thank you @stefan6419846 :hugs: I will release a version of pypdf with the relaxed typing_extensions requirement today to PyPI :-)

2023-08-27 08:39 UTC, stefan6419846 commented
Thanks for your validation and research - a rather unsual issue ;) I just assume that the GitHub tags would be right, but honestly never tested it with version 3.7.4.2 myself.