DOC: Update README.md
py-pdf/pypdf pull request #2232
Opened 2023-10-01 23:30 UTC by mp3403

Added link to CONTRIBUTING.md in the "Contributions" section and added three common questions and answers in the Q&A section.

2023-10-02 06:44 UTC, stefan6419846 commented
Where do these FAQ come from? If ever, shouldn't these rather be part of the official docs instead of the README?

Additionally, the `extractText` method is deprecated in favor of `extract_text`: https://pypdf.readthedocs.io/en/latest/modules/PageObject.html?pypdf._page.PageObject.extractText#pypdf._page.PageObject.extractText

2023-10-02 20:49 UTC, pubpub-zz requested changes

2023-10-02 20:49 UTC, pubpub-zz commented on README.md
> +Use the <code>PdfMerger</code> class. The <code>append</code> method is great for simply concatenating files, but <code>merge</code> can be used
PdfMerger is obsolete. PdfWriter has to be used instead

2023-10-02 20:49 UTC, pubpub-zz commented on README.md
> +There are several ways of extracting text from a pdf file using pypdf. The <code>extractText</code> method is likely the simplest way of doing this.
link to the proper documentation page should be added

2023-10-04 15:14 UTC, MartinThoma commented
The link to CONTRIBUTING is fine. Please remove the rest.

2023-10-07 07:51 UTC, MartinThoma commented on README.md
> +The following is some of the most commonly asked questions:
```suggestion
and asking users who report issues for [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)'s (Code + example PDF!).
```

2023-10-07 07:51 UTC, MartinThoma commented on README.md
> +There are several ways of extracting text from a pdf file using pypdf. The <code>extractText</code> method is likely the simplest way of doing this.
```suggestion
```

2023-10-07 07:52 UTC, merged

2023-10-07 07:52 UTC, pubpub-zz commented
@MartinThoma  Have you consiredered my comments ?

2023-10-07 09:08 UTC, MartinThoma commented
@pubpub-zz I have removed those parts from the PR as they are already covered in a cleaner way in the very top of the PR.

2023-10-07 10:37 UTC, pubpub-zz commented
all good, I was just questionning based on the replies to my comments.

2023-10-07 11:38 UTC, MartinThoma commented
I do agree to the comments :+1:  But I don't think we should add complete paragraphs