BUG: Error when filling a value with parentheses #2268
py-pdf/pypdf pull request #2269
Opened 2023-10-25 16:00 UTC by KanorUbu

Code to fix issue #2268

2023-10-25 17:07 UTC, pubpub-zz requested changes
thanks for your contribution.
2 comments to complete your work

2023-10-25 17:07 UTC, pubpub-zz commented on pypdf/_writer.py
> +        # Escape parentheses (Ref. 7.3.4.2 Literal Strings)
```suggestion
        # Escape parentheses (pdf 1.7 reference, table 3.2  Literal Strings)
```

2023-10-25 17:07 UTC, pubpub-zz commented on pypdf/_writer.py
> +        txt = txt.replace('(', r'\(').replace(')', r'\)')
\ should also be covered
```suggestion
        txt = txt.replace("\\", "\\\\").replace("(", r"\(").replace(")", r"\)")
```

2023-10-26 07:18 UTC, KanorUbu commented
I've considered your feedback

2023-10-26 17:22 UTC, pubpub-zz approved these changes

2023-10-27 07:08 UTC, stefan6419846 commented
Shouldn't we add a test for this as well, at least at a basic level?

2023-10-27 16:43 UTC, pubpub-zz commented
> Shouldn't we add a test for this as well, at least at a basic level?

I've thought about it but the only way is a visual check 🫤. If the test consist in checking replace is working I don't think it worth it

2023-10-28 08:19 UTC, merged

2023-10-28 08:20 UTC, MartinThoma commented
Thank you for your contribution @KanorUbu :pray: 

If you want, I'll add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

2023-10-28 08:20 UTC, MartinThoma commented
And thanks @pubpub-zz / @stefan6419846 for the review :-)